#!/usr/bin/env python

import obspy
import numpy as np
import seispy
from matplotlib import pyplot as plt
import sys


fig = plt.figure(figsize=(13,20))
ax_sec1   = plt.subplot2grid((3,2), (0,0), rowspan=2)
ax_vesp1 = plt.subplot2grid((3,2), (2,0))
ax_sec2   = plt.subplot2grid((3,2), (0,1), rowspan=2)
ax_vesp2 = plt.subplot2grid((3,2), (2,1))
bbax1 = fig.add_axes((0.43,0.34,0.1,0.1))
bbax1.axes.get_yaxis().set_visible(False)
bbax1.axes.get_xaxis().set_visible(False)
bbax1.set_frame_on(False)
bbax1.patch.set_alpha(0)
bbax2 = fig.add_axes((0.85,0.34,0.1,0.1))
bbax2.axes.get_yaxis().set_visible(False)
bbax2.axes.get_xaxis().set_visible(False)
bbax2.set_frame_on(False)
bbax2.patch.set_alpha(0)

phase_dict = {'family' : 'normal',
              'size'   : 10}
#ax_sec1, ax_sec2, ax_vesp1, ax_vesp2, cax, fig = make_figure()

st1 = obspy.read(sys.argv[1])
st2 = obspy.read(sys.argv[2])
st1 = seispy.filter.range_filter(st1,(45,80))
st2 = seispy.filter.range_filter(st2,(45,80))

#st1.filter('highpass',freq=0.3)
st1.normalize()
st1 = seispy.data.align_on_phase(st1)

#st2.filter('highpass',freq=0.3)
st2.normalize()
st2 = seispy.data.align_on_phase(st2)
#######3Section plots

#Top Left
seispy.plot.section(st1,az_color=331,x_lim=(-10,160),ax_grab=ax_sec1,
                    title=False,y_lim=(43,75))

ax_sec1.set_xlabel('')
ax_sec1.xaxis.set_ticklabels([])
ax_sec1.set_title('Event A')
focmec1 = [14,21,-61]
b = obspy.imaging.beachball.Beach(focmec1,xy=(0.5,0.5),width=0.5,linewidth=1,
                                  facecolor='blue')
bbax1.add_collection(b)

ax_sec1.text(0,44,'P',fontdict=phase_dict)
ax_sec1.text(90,44,'PcP',fontdict=phase_dict)
ax_sec1.text(130,73.5,'pP',fontdict=phase_dict)
ax_sec1.text(90,73.5,'1800',fontdict=phase_dict)
ax_sec1.text(65,73.5,'1500',fontdict=phase_dict)
ax_sec1.text(35,73.5,'1150',fontdict=phase_dict)
ax_sec1.tick_params(axis='y', labelsize=10)

#Top Right
seispy.plot.section(st2[::2],x_lim=(-10,160),ax_grab=ax_sec2,
                    title=False,y_lim=(43,75))
ax_sec2.set_xlabel('')
ax_sec2.set_ylabel('')
ax_sec2.xaxis.set_ticklabels([])
ax_sec2.yaxis.set_ticklabels([])
ax_sec2.set_title('Event B')
focmec2 = [349,37,-82]
b = obspy.imaging.beachball.Beach(focmec2,xy=(0.5,0.5),width=0.5,linewidth=1,
                                  facecolor='blue')
bbax2.add_collection(b)

ax_sec2.text(0,44,'P',fontdict=phase_dict)
ax_sec2.text(90,44,'PcP',fontdict=phase_dict)
ax_sec2.text(125,73.5,'pP',fontdict=phase_dict)
ax_sec2.text(20,44,'p410P',fontdict=phase_dict)
ax_sec2.text(40,44,'s410P',fontdict=phase_dict)


####Vespagram plots
#bottom left
st1 = seispy.filter.az_filter(st1,(270,330))
st1.differentiate()
st1.normalize()
st1 = seispy.data.align_on_phase(st1)
image1 = seispy.plot.vespagram(st1,ax_grab=ax_vesp1,title=False,x_lim=(-10,160))
ax_vesp1.grid()
ax_vesp1.set_ylabel('Slowness')
ax_vesp1.set_xlabel('Seconds after P')
ax_vesp1.tick_params(axis='y', labelsize=10)
ax_vesp1.tick_params(axis='x', labelsize=10)

#bottom right
st2 = seispy.filter.az_filter(st2,(270,330))
st2.differentiate()
st2.normalize()
st2 = seispy.data.align_on_phase(st2)
image2 = seispy.plot.vespagram(st2,ax_grab=ax_vesp2,title=False,x_lim=(-10,160))
ax_vesp2.yaxis.set_ticklabels([])
ax_vesp2.grid()
ax_vesp2.set_xlabel('Seconds after P')
ax_vesp2.tick_params(axis='x', labelsize=10)

####Colorbar
bbox = ax_vesp2.get_position()
xmax = bbox.xmax
ymin = bbox.ymin
ymax = bbox.ymax

cax = fig.add_axes((xmax+0.02,ymax,0.02,ymin-ymax))
cbar = fig.colorbar(image1,cax=cax,orientation='vertical')
cbar.ax.invert_yaxis()
cbar.set_ticks([0,-1,-2,-3])
cbar.set_label(r'$\log(Amplitude)$')

plt.show()





