#!/usr/bin/env python

import obspy
import h5py
import glob
import pandas
import os

def main():
    st_n = obspy.core.Stream()
    st_e = obspy.core.Stream()
    st_z = obspy.core.Stream()

    info_list, CMT_list, inparam_list, station_list = open_files()

    seis_list = glob.glob('./SEISMOGRAMS/*.dat')

    stat_name_list = []
    for ii in station_list:
        stat_name_list.append(ii[0])
    seis_len = float(inparam_list[16].split()[1])
    start = obspy.core.UTCDateTime(0)
    end = start+seis_len
    npts = float(info_list[2].strip().split()[0])
    sampling_rate = npts/seis_len
    delta = 1./sampling_rate

    evla = CMT_list[0]
    evlo = CMT_list[1]
    evdp = CMT_list[2]

    for ii in seis_list:
        tr = obspy.core.Trace()
        network = ii.split('/')[-1].split('_')[1]
        station = ii.split('/')[-1].split('_')[0]
        if station == 'STAT' or station == 'STATneg':
            station = ii.split('/')[-1].split('_')[0]+'_'+\
                      ii.split('/')[-1].split('_')[1]
        channel = ii.split('/')[-1].split('_')[-1][0]
        data = pandas.read_csv(ii,
                        sep=r"\s*",engine='python')
        data = data.as_matrix()[:,1]
        tr.stats.network = network
        tr.stats.station = station
        tr.stats.channel = channel
        tr.stats.starttime = start
        tr.stats.sampling_rate = sampling_rate
        tr.stats.delta = delta
        tr.stats.npts = npts
        tr.data = data
        tr.stats.sac = {}

        tr.stats.sac['evdp'] = evdp
        tr.stats.sac['evla'] = evla
        tr.stats.sac['evlo'] = evlo
        tr.stats.sac['o'] = 0

        index = stat_name_list.index(station)
        if len(station_list[index]) == 6:
            tr.stats.sac['stla'] = float(station_list[index][2])
            tr.stats.sac['stlo'] = float(station_list[index][3])
            tr.stats.sac['gcarc'] = 0
            tr.stats.sac['az'] = 0
            tr.stats.sac['baz'] = 0
        else:
            tr.stats.sac['stla'] = float(station_list[index][2])
            tr.stats.sac['stlo'] = float(station_list[index][3])
            tr.stats.sac['gcarc'] = float(station_list[index][5])
            tr.stats.sac['az'] = float(station_list[index][6])
            tr.stats.sac['baz'] = float(station_list[index][7])

        if channel == 'E':
            st_e.append(tr)
        if channel == 'N':
            st_n.append(tr)
        if channel == 'Z':
            st_z.append(tr)
    st_n.write('st_N.pk',format='PICKLE')
    st_e.write('st_E.pk',format='PICKLE')
    st_z.write('st_Z.pk',format='PICKLE')

def open_files():
    info_file = open('./simulation.info')
    info_list = info_file.read().strip().split('\n')

    try:
        CMT_file = open('./CMTSOLUTION')
        CMT_list = CMT_file.read().strip().split('\n')
        evla = float(CMT_list[4].split()[1])
        evlo = float(CMT_list[5].split()[1])
        evdp = float(CMT_list[6].split()[1])
        CMT_list = [evla, evlo, evdp]
    except IOError:
        CMT_list = [90,0,0]

    inparam_basic_file = open('./inparam_basic')
    inparam_list = inparam_basic_file.read().strip().split('\n')

    station_file = open('./STATIONS')
    station_list = [line.strip().split() for line in station_file]
    return info_list, CMT_list, inparam_list, station_list

main()
